### ISSUE TITLE
Mock errors documentation

### ISSUE THREAD

**Issue by pabloyoyoista** [martinpitt/python-dbusmock#102]
Hello,

I have found this tool super useful for doing some testing, thank you for making it! I have been following the documentation and writing the first tests with some success. However, I also wanted to mock errors and I haven't figured out a way to do it. Is it currently implemented/documented? For example, the idea is that a method that only has one input, but no output, can potentially consider the input invalid and produce an error. Is it possible to mock this behavior?

**Comment by martinpitt** [comment]
Yes, of course -- your mock methods can call `dbus.exceptions.DBusException` as usual. The existing templates do that a lot, see e.g. [accounts-service FindUserById()](https://github.com/martinpitt/python-dbusmock/blob/a51ad658e07504bfd87f1565400a7b9d125b4855/dbusmock/templates/accounts_service.py#L215) for a typical use case.

I'll keep this open to improve documentation.

**Comment by pabloyoyoista** [comment]
Thank you very much! I don't think I would have figured it out, adding it to the docs could help other newbies, yes :)

**Comment by martinpitt** [comment]
I sent PR #104 to overhaul the documentation a little bit, including raising exceptions.
