### ISSUE TITLE
Support using dbus-broker instead of dbus-daemon

### ISSUE THREAD

**Issue by jadahl** [martinpitt/python-dbusmock#165]
python-dbusmock currently works by spawning a `dbus-daemon` for each mocked bus. It'd be nice if it also knew how to do the equivalent but using `dbus-broker` instead, so that one can use python-dbusmock on a system that doesn't come with `dbus-daemon` but only `dbus-broker`.

**Comment by martinpitt** [comment]
I agree, that'd be nice! Do you happen to know how to drive this properly?

```sh
cat <<EOF > /tmp/c.conf
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-Bus Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <type>session</type>
  <keep_umask/>
  <listen>unix:tmpdir=/tmp</listen>
  <!-- We do not add standard_session_servicedirs (i.e. we only have our private services directory). -->
  <servicedir>/tmp/d/services</servicedir>

  <policy context="default">
    <allow send_destination="*" eavesdrop="true"/>
    <allow eavesdrop="true"/>
    <allow own="*"/>
  </policy>
</busconfig>
EOF
```

```
❱❱❱ dbus-broker-launch --config /tmp/c.conf 
No listener socket inherited
```
It seems a bit awkward having to create a socket and passing it in via the systemd fd activation protocol. Is there some way to make it similar to `dbus-daemon` or `dbus-launch`?

**Comment by jadahl** [comment]
> Do you happen to know how to drive this properly?

I'm afraid I don't :|

**Comment by martinpitt** [comment]
Meh, it seems dbus-broker is rather insistent on being run with systemd. It considers a missing journal service as fatal:

```
418   connect(4, {sa_family=AF_UNIX, sun_path="/run/systemd/journal/socket"}, 29) = -1 ENOENT (No such file or directory)
418   write(2, "ERROR launcher_open_log @ ../src/launch/launcher.c +179: No such file or directory\n", 83) = 83
418   close(4)                          = 0
418   write(2, "      launcher_new @ ../src/launch/launcher.c +210\n", 51) = 51
418   close(3)                          = 0
418   write(2, "      run @ ../src/launch/main.c +149\n", 38) = 38
418   rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
418   write(2, "      main @ ../src/launch/main.c +178\n", 39) = 39
418   write(2, "Exiting due to fatal error: -2\n", 31) = 31
418   exit_group(1)                     = ?
```

This happens [here](https://github.com/bus1/dbus-broker/blob/main/src/launch/launcher.c#L161). I'm afraid this is a hard blocker -- dbusmock is meant to run in build chroots, unprivileged environments and such. The manpage says

> By default, dbus-broker-launch logs messages to the system journal.

but does not document an alternative, and the code doesn't have any either.

So I'm afraid this just can't work, sorry.

**Comment by jadahl** [comment]
Thanks for trying!
