### ISSUE TITLE
Support loading templates from a shared location

### ISSUE THREAD

**Issue by pwithnall** [martinpitt/python-dbusmock#168]
It would be useful if there could be a well-defined location to load templates from, which third party projects could install their templates to without having to submit them as PRs here. That would remove some maintenance burden from python-dbusmock itself, and remove a barrier to using it for third party projects which are used by other third party projects and hence can’t just easily use an in-tree template.

Specifically, I’d like to add a template for eos-updater for consumption by gnome-software, but it seems a bit niche to submit to python-dbusmock.git. So I’d like to be able to install it to (say) `/usr/share/python-dbusmock/templates/eos_updater.py` and have `python3 -m dbusmock -t eos_updater` find it.

I don’t think this is supported already? Thanks

**Comment by martinpitt** [comment]
Indeed I never meant to funnel all mocks and templates through my upstream repo -- some popular ones make sense there, but there's already too many fringe ones around.

Specifying a custom template file is already supported with e.g.

    python3 -m dbusmock --session -t /tmp/sensors.py

and with the API:

    self.spawn_server_template('/tmp/sensors.py')

Isn't that good enough? I'd say for tests it's rather impractical to first have to put the templates into the file system, it feels much more natural to run them out of a source tree?

**Comment by pwithnall** [comment]
> Specifying a custom template file is already supported with e.g.
> 
> ```
> python3 -m dbusmock --session -t /tmp/sensors.py
> ```

That’s good, but I think it would help if there was a canonical shared location for these templates, and python-dbusmock could look there without users having to specify the full path.

Or if you don’t want to do that, documenting a canonical shared location would be useful to ensure that third-party projects install their templates in consistent places.

Then, for example, eos-updater could install its `eos_updater.py` template as part of the `eos-updater-dev` package, and anyone wanting to test gnome-software against it could install that rather than having to check out eos-updater.git.

**Comment by martinpitt** [comment]
I sent an implementation to PR #169. Please let me know what you think! (Still working out some pylint etc. issues)
