### ISSUE TITLE
powerprofilectl started to SIGTRAP in Fedora Rawhide

### ISSUE THREAD

**Issue by martinpitt** [martinpitt/python-dbusmock#177]
The [recent runs](https://github.com/martinpitt/python-dbusmock/actions/runs/5618534753/job/15238470263) started to fail like this:
```
test_list_holds (tests.test_power_profiles_daemon.TestPowerProfilesDaemon.test_list_holds)
Test holds ... 
(process:714): GLib-CRITICAL **: 14:41:31.101: g_main_context_release() called on a context (0x564d6af1c0d0, owner 0x564d6af16eb0, owner count 3) which is not acquired by the current thread
ERROR
[...]
======================================================================
ERROR: test_list_holds (tests.test_power_profiles_daemon.TestPowerProfilesDaemon.test_list_holds)
Test holds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/source/tests/test_power_profiles_daemon.py", line 80, in test_list_holds
    out = self.run_powerprofilesctl_list_holds()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/tests/test_power_profiles_daemon.py", line 73, in run_powerprofilesctl_list_holds
    return subprocess.check_output(['powerprofilesctl', 'list-holds'],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['powerprofilesctl', 'list-holds']' died with <Signals.SIGTRAP: 5>.
```

The other two tests fail in the same way. It's a race condition, it doesn't always happen. E.g. in [this run](https://github.com/martinpitt/python-dbusmock/actions/runs/5618534753/job/15224278017), one test passed and the other two failed.

@hadess , there [was no recent p-p-d update](https://bodhi.fedoraproject.org/updates/?packages=power-profiles-daemon), perhaps this coincides with [glib 2.77.0-7](https://bodhi.fedoraproject.org/updates/FEDORA-2023-c2da2a8e29)?

**Comment by martinpitt** [comment]
Hmm, when I run the tests in isolation:

    python3 -m unittest -v tests.test_power_profiles_daemon.TestPowerProfilesDaemon

they still show the Glib-CRITICAL about g_main_context_release(), but don't fail.

I downgraded glib:

    dnf install https://kojipkgs.fedoraproject.org//packages/glib2/2.77.0/6.fc39/x86_64/glib2-2.77.0-6.fc39.x86_64.rpm

and it still fails. The [-7 change](https://bodhi.fedoraproject.org/updates/FEDORA-2023-c2da2a8e29) also sounded harmless enough. The log between the last working and first failing run only shows systemd 254~rc2-1.fc39 → 254~rc2-4.fc39.

Downgrading to that:

    dnf install https://kojipkgs.fedoraproject.org//packages/systemd/254~rc2/1.fc39/x86_64/systemd-254~rc2-1.fc39.x86_64.rpm https://kojipkgs.fedoraproject.org//packages/systemd/254~rc2/1.fc39/x86_64/systemd-libs-254~rc2-1.fc39.x86_64.rpm https://kojipkgs.fedoraproject.org//packages/systemd/254~rc2/1.fc39/x86_64/systemd-networkd-254~rc2-1.fc39.x86_64.rpm https://kojipkgs.fedoraproject.org//packages/systemd/254~rc2/1.fc39/x86_64/systemd-pam-254~rc2-1.fc39.x86_64.rpm https://kojipkgs.fedoraproject.org//packages/systemd/254~rc2/1.fc39/x86_64/systemd-resolved-254~rc2-1.fc39.x86_64.rpm https://kojipkgs.fedoraproject.org//packages/systemd/254~rc2/1.fc39/x86_64/systemd-udev-254~rc2-1.fc39.x86_64.rpm

does not fix the test either.

@hadess Does that tell anything to you?

**Comment by hadess** [comment]
I would try to set `G_DEBUG=fatal_warnings` and use [`catchsegv`](https://github.com/zatrazz/glibc-tools.git) to grab the backtrace from that.

Looking at https://gitlab.gnome.org/GNOME/glib/-/issues/3054 it's likely a bug in one of the libraries it loads.

**Comment by martinpitt** [comment]
I ran `G_DEBUG=fatal-warnings catchsegv python3 -m unittest -v, and that didn't actually print out anything extra. But I'll just retry this in a few weeks, when that bug fix appears in the next glib release.

**Comment by martinpitt** [comment]
Nice, glib2 2.77.1 is in Rawhide now. Locally the tests pass again. Sent #181
