### ISSUE TITLE
Missing ivp4/ipv6 sections in `AddWiFiConnection`

### ISSUE THREAD

**Issue by souliane** [martinpitt/python-dbusmock#198]
Thanks again for this project!

I am using `AddWiFiConnection`, but when I retrieve the connection settings with [GetSettings](https://networkmanager.dev/docs/api/latest/gdbus-org.freedesktop.NetworkManager.Settings.Connection.html#gdbus-method-org-freedesktop-NetworkManager-Settings-Connection.GetSettings) , the sections for `ipv4` and `ipv6` are missing. If I am not mistaken, the settings that are created by the mock function have been simplified on purpose.
Is it possible to add them (even with empty values, to keep retro-compatibility), so that calling `GetSettings` returns output data that looks real? 

I think that an alternative would be to update the settings afterward by using `ConnectionUpdate`. Or is there a better solution?

**Comment by martinpitt** [comment]
@souliane Indeed AddWiFiConnection() documents "Please note that this does not set any global properties.". TBH I don't know much about the NM template, I neither wrote (most of it) nor use it myself.

However, I don't mind stubbing it out a bit. There are a lot of settings in ipv4/6, fortunately they all seem to have proper default values. I sent PR #199 for this, can you please check if that's what you want/need?

**Comment by souliane** [comment]
Hi Martin,
Thanks a lot for taking care of this!
It is enough for the usecase I had (I just needed to get an entry for ipv4 or ipv6).
To be honest, I don't need it anymore because I will test differently, but since this is ready, I think that it would be good to merge it :-)
