### ISSUE TITLE
Add gnome-session template

### ISSUE THREAD

**Issue by hadess** [martinpitt/python-dbusmock#27]
gnome-settings-daemon's tests currently use a real gnome-session. However, gnome-session relies on logind functionality that cannot be mocked (`sd-login.h` functions which use cgroups). To bring back the tests, we'd need to have a mocked gnome-session service.

**Comment by martinpitt** [comment]
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/blob/master/tests/gsdtestcase.py runs a real gnome-session on top of a mocked logind. Is that enough, or do we still need a g-session mock? As I've been out of GNOME development for a fair while, do you have a pointer to the API, and which (old?) tests should run against that? If we add a template, I'd like to create tests for it in the usual manner -- preferably the "real" CLI consumers of that API, but some direct D-Bus calls ought to do as well (as I figure there may not actually be a "gnome-session CLI" in the spirit of /usr/bin/upower or `nm-cli`). Thanks!

**Comment by hadess** [comment]
I honestly don't remember. I made this change a couple of hours before filing this bug:
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/commit/f581667b187b38ff45f27e6eba62f30482fba1ee

So I guess that having a deterministic mock gnome-session was still something that I considered useful. I'm not directly involved in gnome-settings-daemon development anymore, so I'll close this.
