### ISSUE TITLE
All dbus.exceptions.DBusExceptions are instansiated incorrectly

### ISSUE THREAD

**Issue by semafor** [martinpitt/python-dbusmock#3]
It seems `dbus.exceptions.DBusException` takes a `name` keyword argument per [1]. This means that

    raise dbus.exceptions.DBusException('org.bluez.Error.NoSuchAdapter',
        'No such adapter.')

will raise an exception that is not named `org.bluez.Error.NoSuchAdapter`, but rather named `org.freedesktop.DBus.Python.dbus.exceptions.DBusException`. Code expecting specific exceptions will thus not work as expected.

[1] http://dbus.freedesktop.org/doc/dbus-python/api/dbus.exceptions.DBusException-class.html

**Comment by martinpitt** [comment]
Thanks for pointing out! Fixed in https://github.com/martinpitt/python-dbusmock/commit/4fc6a4a5a98f32c9c9d64597e4e5dddb7f321fdf
