### ISSUE TITLE
Evaluate patches from OpenEmbedded

### ISSUE THREAD

**Issue by mardy** [martinpitt/python-dbusmock#36]
Hi Martin!
  In OpenEmbedded they are keeping a couple of patches to python-dbusmock:
    http://cgit.openembedded.org/meta-openembedded/tree/meta-python/recipes-devtools/python/python-dbusmock

Were these patches submitted to you? If not, would you like them to get submitted?
The commit messages are not explicative enough for me to understand what exactly their point is, but I believe you might be able to see it. :-)

**Comment by martinpitt** [comment]
No, they were not submitted. At first sight they look interesting, although I don't fully understand these yet. Submitting them as PRs with tests (which will then also clarify how to use them) and proper docstrings would be much appreciated!

**Comment by martinpitt** [comment]
python-dbusmock does not exist any more in http://cgit.openembedded.org/meta-openembedded/tree/meta-python/recipes-devtools/python , so this looks obsolete now. If you still have patches, please by all means submit them. Thanks!
