### ISSUE TITLE
Network manager 1.10 changes some output

### ISSUE THREAD

**Issue by BryanQuigley** [martinpitt/python-dbusmock#37]
NetworkManager versions 1.10+ have shorter names, not sure the best way this should be done as we likely want old version compatible too?  Attached patch "fixes" it, but doesn't maintain backward compatibility nor does it handle the negative asserts in the code.

[patch.txt](https://github.com/martinpitt/python-dbusmock/files/1717753/patch.txt)

**Comment by martinpitt** [comment]
These are all regular expressions, so they should be changed to `(802-11-wireless|wifi)` to work for older versions too.

**Comment by seb128** [comment]
The format changed with that commit
https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=6fde475b
