### ISSUE TITLE
Tests fail to run in fakeroot

### ISSUE THREAD

**Issue by z3ntu** [martinpitt/python-dbusmock#46]
Hello (again),

I'm trying to package up python-dbusmock for Alpine but while running the tests I noticed that when they are run in fakeroot, they completely error out. (log: https://pastebin.com/raw/ecnNA85J)

I don't know the exact behavior of fakeroot, but doing root->fakeroot then the tests work, just in non-root-user->fakeroot they fail.

Outside of the fakeroot (both as root or non-root user) they work fine.

CC @PureTryOut

**Comment by martinpitt** [comment]
I can reproduce this easily with fakeroot in Debian, but I'm afraid there's not much I can do on the python-dbusmock side:
```
$ fakeroot bash
$ export DBUS_SESSION_BUS_ADDRESS=$(dbus-daemon --fork --print-address=1 --print-pid=2 --session)
$ dbus-send --session --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.Hello
Failed to open connection to "session" message bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

I suggest running the tests with `env -u LD_PRELOAD` to skip fakeroot for the tests.
