### ISSUE TITLE
templates for mocking systemd unit actions

### ISSUE THREAD

**Issue by nand0p** [martinpitt/python-dbusmock#49]
would it be possible to add templates or documentation for mocking out interaction with systemd services?  such as restarting nginx or sshd?

```
dbus_path = '/org/freedesktop/systemd1'
dbus_object = 'org.freedesktop.systemd1'
dbus_interface = 'org.freedesktop.systemd1.Manager'
systemd_service = 'sshd.service'

def _trigger_dbus(self, dbus_object, dbus_path, dbus_interface, systemd_service):
    sysbus = dbus.SystemBus()
    systemd1 = sysbus.get_object(dbus_object, dbus_path)
    manager = dbus.Interface(systemd1, dbus_interface)
    restart_out = manager.RestartUnit(systemd_service, 'fail')
    self.out.write('systemd unit restart: {}\n'.format(restart_out))
```

this is the working code i would like to test with dbus mocking.

**Comment by martinpitt** [comment]
Sure, you can add any methods with any behaviour/return value you like. That's the primary purpose of dbusmock. :smile: 

The documentation has plenty of examples. If it's unclear somewhere, it's a great opportunity to fix it of course! Where do you run into trouble?

**Comment by paulohefagundes** [comment]
+1 it would be nice to have a template for systemd, a basic one with at least these APIs would be great
- StartUnit
- StopUnit
- RestartUnit
- EnableUnitFiles
- DisableUnitFiles
- GetUnitFileState

https://www.freedesktop.org/wiki/Software/systemd/dbus/

**Comment by nand0p** [comment]
this is fairly straightforward to do. no need to have explicit example i guess. closing issue.
