### ISSUE TITLE
Add Custom Functions for Return Value of Mocked DBus Methods

### ISSUE THREAD

**Issue by pclass-sensonix** [martinpitt/python-dbusmock#60]
Hi. First, thanks for the excellent work on this module. I'm finding it extremely useful for testing my code.

I looked through each and every test file under the /tests directory for an example of how to pass a custom function to the "AddMethod", rather than a string containing 'ret = X' as shown below:

`self.dbus_mock.AddMethod('', 'Do', 'si', 's', 'ret = args[0] * args[1]')`

Is there a way to pass a function instead of the 'ret = X' such as this:

```
def retVal(a):
    return a + 1

...

self.dbus_mock.AddMethod('', 'Do', 'i', 'i', reVal)
```

**Comment by martinpitt** [comment]
You closed this yourself, so I suspect you already figured it out by yourself. You can do that, it's just Python. dbusmock/templates/networkmanager.py and dbusmock/templates/urfkill.py do that for example.
