### ISSUE TITLE
How to add devices to NetworkManager template from the command line?

### ISSUE THREAD

**Issue by mattdibi** [martinpitt/python-dbusmock#73]
Hi,

first of all thank you for this awesome project.

I'm having a hard time in figuring out how to properly mock a simple NetworkManager instance from the command line.
When I run:
```
$ python3 -m dbusmock --template networkmanager
```
I get a mock NetworkManager but it doesn't provide any network device nor anything (`nmcli device show` doesn't show anything, nor does `nmcli`)

```
$ nmcli --nocheck general
STATE      CONNECTIVITY  WIFI-HW  WIFI     WWAN-HW  WWAN     
connected  full          enabled  enabled  enabled  disabled
```

```
$ nmcli --nocheck networking
enabled
```

```
$ nmcli --nocheck dev       


```

I tried adding devices through the `-p` optional argument but nothing changed.

```
$ python3 -m dbusmock --template networkmanager -p '{"Devices": "eth0"}'
```

What am I doing wrong? What's the proper way to add a mock device?

#### Additional informations:
- **python-dbusmock version**: 0.23.0
- **OS**: Ubuntu 19.10

**Comment by mattdibi** [comment]
Nevermind, I ended up modifying the main by adding devices manually like so:

```py
    eth0 = main_object.AddEthernetDevice('mock_Ethernet1', 'eth0', 30)
    eth1 = main_object.AddEthernetDevice('mock_Ethernet2', 'eth1',
                                        DeviceState.ACTIVATED)
```

Still having trouble with the ipv4 properties though. It would be nice to have an example on how to properly add devices and properties for the networkmanager mock.

**Comment by martinpitt** [comment]
@mattdibi : Have a look at the comments in the public functions (dbus.service.method) of the [template](https://github.com/martinpitt/python-dbusmock/blob/master/dbusmock/templates/networkmanager.py). The [integration tests](https://github.com/martinpitt/python-dbusmock/blob/master/tests/test_networkmanager.py) also run a lot of scenarios, and thus are good examples. 

With dbusmock you normally set up and change templates through the `org.freedesktop.DBus.Mock` interface, which you can do on the command line (with e.g. `busctl`) or more comfortably from Python or other languages; see README.
