### ISSUE TITLE
NetworkManager mock should support connecting to non-existant access points

### ISSUE THREAD

**Issue by semafor** [martinpitt/python-dbusmock#8]
A user can have a typo in an SSID. Currently, the NetworkManager mock will raise an exception in this case, but NetworkManager allows this and will communicate the error through a device's state.

See [1] and `NM_DEVICE_STATE_REASON_SSID_NOT_FOUND`, which means "The 802.11 Wi-Fi network could not be found. "

[1] https://developer.gnome.org/NetworkManager/0.9/spec.html#type-NM_DEVICE_STATE_REASON

**Comment by martinpitt** [comment]
This was apparently fixed years ago already. I now added a `nmcli dev wifi connect nonexisting` test case to make sure it works fine.

**Comment by martinpitt** [comment]
Done in commit b05ad953274c7d7a0f92fc4d32bc0cc00fe36690 , I just botched the syntax for auto-closing.
